--EJ1

CREATE OR REPLACE VIEW DEPARTAM
AS SELECT DEPART.DEPT_NO,DNOMBRE,LOC,DECODE(COUNT(*),0,0,COUNT(*)) EMPLEADOS FROM EMPLE
           RIGHT JOIN DEPART ON EMPLE.DEPT_NO = DEPART.DEPT_NO
           GROUP BY DEPART.DEPT_NO,DNOMBRE,LOC;
           
           
CREATE OR REPLACE TRIGGER EJ1
INSTEAD OF INSERT OR UPDATE OR DELETE
ON DEPARTAM 
FOR EACH ROW
BEGIN 
    IF INSERTING THEN
        INSERT INTO DEPART VALUES (:NEW.DEPT_NO,:NEW.DNOMBRE,:NEW.LOC);
    ELSIF DELETING THEN
        DELETE DEPART WHERE DEPT_NO=:OLD.DEPT_NO;
    ELSIF UPDATING('LOC') THEN
        UPDATE DEPART SET LOC = :NEW.LOC WHERE DEPT_NO = :NEW.DEPT_NO;
    ELSE
        RAISE_APPLICATION_ERROR(-20010,'No se puede realizar la acción');
    END IF;
END;

INSERT INTO DEPARTAM VALUES(50,'TEST','TEST',0); --INSERTING OK
DELETE DEPARTAM WHERE DEPT_NO=50; --DELETING OK
UPDATE DEPARTAM SET LOC = 'Test' WHERE DEPT_NO=20; --UPDATING OK
UPDATE DEPARTAM SET DNOMBRE='Test' WHERE DEPT_NO=20; --RESTO OPERACIONES OK


--EJ2

CREATE OR REPLACE VIEW paises_europa_vista
AS
SELECT cod_pais, nombre, capital, num_hab/extension densidad,
 (SELECT nombre FROM ciudad WHERE cod_pais=pais.cod_pais AND habitantes=(SELECT MAX(habitantes) FROM ciudad
 WHERE cod_pais=pais.cod_pais)) ciudadmaspoblada,
 (SELECT habitantes FROM ciudad
 WHERE cod_pais=pais.cod_pais
 AND habitantes=(SELECT MAX(habitantes) FROM ciudad
 WHERE cod_pais=pais.cod_pais)) habciudadmaspoblada
FROM pais
WHERE continente='Europa'
ORDER BY densidad DESC
WITH CHECK OPTION; 

CREATE OR REPLACE TRIGGER TRG_PAISES_EUROPA
INSTEAD OF INSERT OR DELETE OR UPDATE ON paises_europa_vista
    DECLARE
    v_ciudadMasPoblada PAISES_EUROPA_VISTA.ciudadmaspoblada%TYPE;
    BEGIN
        IF INSERTING OR UPDATING THEN 
            INSERT INTO PAIS(COD_PAIS,NOMBRE,CAPITAL,CONTINENTE) VALUES (:NEW.COD_PAIS,:NEW.NOMBRE,:NEW.CAPITAL,'EUROPA');
                SELECT CIUDADMASPOBLADA INTO v_ciudadMasPoblada FROM PAISES_EUROPA_VISTA WHERE COD_PAIS = :NEW.COD_PAIS;
            INSERT INTO CIUDAD VALUES (:new.cod_pais,v_ciudadMasPoblada,:new.habciudadmaspoblada);
        ElSIF DELETING THEN
            DELETE CIUDAD WHERE COD_PAIS = :OLD.COD_PAIS;
            DELETE PAIS WHERE COD_PAIS = :OLD.COD_PAIS;
        END IF;
        END;