--EJ1

CREATE TABLE superpotencias AS
SELECT *
FROM pais
WHERE ((pib*1000000)/num_hab) >= 40000
ORDER BY pib/num_hab DESC;


CREATE OR REPLACE TRIGGER TRG_SUPERPOTENCIAS
AFTER INSERT OR UPDATE OR DELETE ON PAIS 
FOR EACH ROW
DECLARE
v_existe number;
BEGIN
    IF INSERTING THEN
        IF (:NEW.PIB>40000) THEN
            INSERT INTO superpotencias VALUES (:NEW.COD_PAIS,:NEW.NOMBRE,:NEW.CAPITAL,:NEW.EXTENSION,:NEW.MONEDA,:NEW.NUM_HAB,:NEW.PIB,:NEW.CONTINENTE);
        END IF;
    ELSIF UPDATING THEN
            IF (:NEW.PIB<40000) THEN
                DELETE superpotencias WHERE COD_PAIS=:NEW.COD_PAIS;
            ELSE
                SELECT COUNT(*) INTO v_existe FROM superpotencias WHERE COD_PAIS=:NEW.COD_PAIS;
                IF(v_existe>0) THEN
                    UPDATE superpotencias SET NOMBRE=:NEW.NOMBRE,CAPITAL=:NEW.CAPITAL,EXTENSION=:NEW.EXTENSION,MONEDA=:NEW.MONEDA,NUM_HAB=:NEW.NUM_HAB,PIB=:NEW.PIB,CONTINENTE=:NEW.CONTINENTE
                    WHERE COD_PAIS = :NEW.COD_PAIS;
                ELSE
                    INSERT INTO superpotencias VALUES (:NEW.COD_PAIS,:NEW.NOMBRE,:NEW.CAPITAL,:NEW.EXTENSION,:NEW.MONEDA,:NEW.NUM_HAB,:NEW.PIB,:NEW.CONTINENTE);
                END IF;
           END IF;
    ELSE
        DELETE superpotencias WHERE COD_PAIS=:OLD.COD_PAIS;
    END IF;
END;

INSERT INTO PAIS VALUES (600,'TEST','TEST',300,'TEST',300,40001,'TEST');--INSERTING OK
UPDATE PAIS SET PIB = 20 WHERE COD_PAIS=500;--DELETING OK IF PIB <40000
UPDATE PAIS SET PIB = 90000  WHERE COD_PAIS=600; --UPDATING OK IF PIB >=40000 --IF EXIST
UPDATE PAIS SET PIB = 99000 WHERE COD_PAIS=23; --INSERTING OK IF PIB>=40000 AND NOT EXIST
DELETE PAIS WHERE COD_PAIS=23; --DELETING OK


--EJ2

CREATE OR REPLACE TRIGGER TRG_PAIS_1
AFTER INSERT OR DELETE ON PAIS
FOR EACH ROW
DECLARE
    CURSOR c_1 IS SELECT COD_PAIS,PIB FROM top_10_potencias_por_pib ORDER BY PIB DESC;
    v_registro c_1%ROWTYPE;
BEGIN
    IF INSERTING THEN
        OPEN c_1;
        FETCH c_1 INTO v_registro;
        WHILE(c_1%ROWCOUNT<=10 AND c_1%FOUND) LOOP
            IF(c_1%ROWCOUNT=10) THEN
                IF(v_registro.PIB < :NEW.PIB) THEN
                    DELETE top_10_potencias_por_pib WHERE COD_PAIS=:NEW.COD_PAIS;
                    INSERT INTO top_10_potencias_por_pib VALUES (:NEW.COD_PAIS,:NEW.NOMBRE,:NEW.PIB,:NEW.CAPITAL);
                END IF;
            END IF;
        END LOOP;
        CLOSE c_1;
    END IF;
END;

SELECT COD_PAIS ,PIB FROM top_10_potencias_por_pib WHERE PIB=(SELECT MIN(PIB) FROM top_10_potencias_por_pib);
INSERT INTO PAIS VALUES (169,'TEST','TEST',300,'TEST',30,1826895,'TEST');