--EJ1
CREATE TABLE PAISES_SUPERPOBLADOS AS
 SELECT cod_pais, nombre, num_hab, extension, num_hab/extension AS densidad
 FROM pais
 WHERE num_hab > 90000000; 


CREATE OR REPLACE TRIGGER TRG_SUPERPOBLACION
AFTER INSERT OR DELETE OR UPDATE ON PAIS
FOR EACH ROW
WHEN (new.num_hab > 90000000 OR old.num_hab > 90000000)
BEGIN
    IF INSERTING THEN
        INSERT INTO PAISES_SUPERPOBLADOS VALUES (:NEW.COD_PAIS,:NEW.NOMBRE,:NEW.NUM_HAB,:NEW.EXTENSION,(:NEW.NUM_HAB)/:NEW.EXTENSION);
    ELSIF DELETING THEN
        DELETE PAISES_SUPERPOBLADOS WHERE COD_PAIS = :OLD.COD_PAIS;
    ELSIF UPDATING THEN
        DECLARE
            v_codPais PAISES_SUPERPOBLADOS.COD_PAIS%TYPE;
        BEGIN --NO USAR BLOQUES ANONIMOS USAR COUNT PARA SABER SI EXISTE
            SELECT COD_PAIS INTO v_codPais FROM PAISES_SUPERPOBLADOS WHERE COD_PAIS = :NEW.COD_PAIS;--AQUI USAR COUNT
            IF(:NEW.NUM_HAB < 90000000) THEN
                DELETE PAISES_SUPERPOBLADOS WHERE COD_PAIS = :NEW.COD_PAIS;
            ELSE
                UPDATE PAISES_SUPERPOBLADOS SET COD_PAIS = :NEW.COD_PAIS,NOMBRE = :NEW.NOMBRE,NUM_HAB = :NEW.NUM_HAB,EXTENSION=:NEW.EXTENSION,DENSIDAD= (:NEW.NUM_HAB)/:NEW.EXTENSION
                WHERE COD_PAIS =:OLD.COD_PAIS;
            END IF;
        EXCEPTION 
            WHEN NO_DATA_FOUND THEN
                IF(:NEW.NUM_HAB>=90000000) THEN
                    INSERT INTO PAISES_SUPERPOBLADOS VALUES (:NEW.COD_PAIS,:NEW.NOMBRE,:NEW.NUM_HAB,:NEW.EXTENSION,(:NEW.NUM_HAB)/:NEW.EXTENSION);
                END IF;
        END;
    END IF;
EXCEPTION 
    WHEN dup_val_on_index THEN
        DBMS_OUTPUT.PUT_LINE('El país ya existe');
END;
